# This is a deveopment Docker Compose file
# Sample usage: docker compose -f compose.dev-base.yml up -d

# All volumes declared here
volumes:
  neo4j-main-vol:
  minio-vol:
  redis-vol:
  mongo-vol:
  base-app-vol:
    driver: local
    driver_opts:
      type: none
      device: $PWD/base-app
      o: bind

services:

# Base Application Service
  base-app:
    image: node:alpine
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
    command: "npm run dev"
    restart: always

    ports:
      - published: 80
        target: 80

    volumes:
    - type: volume
      source: base-app-vol
      target: /usr/src/app

# Main Neo4j Service
  neo4j-main:
    image: neo4j
    restart: always
    
    environment:
    - NEO4J_AUTH=none
    - NEO4J_PLUGINS=["apoc","graph-data-science"]

    ports:
    - published: 7474
      target: 7474
    - published: 7687
      target: 7687
    
    volumes:
    - type: volume
      source: neo4j-main-vol
      target: /data

# MinIO Service
  minio:
    image: minio/minio
    restart: always

    environment:
      - MINIO_ROOT_USER=myminioadmin
      - MINIO_ROOT_PASSWORD=myminioadmin

    command: minio server /data --console-address ":9001"

    ports:
      - published: 9000
        target: 9000
      - published: 9001
        target: 9001

    volumes:
    - type: volume
      source: minio-vol
      target: /data

# Redis Service
  redis:
    image: redis:alpine
    restart: always

    command: redis-server --loglevel warning

    volumes:
    - type: volume
      source: redis-vol
      target: /data

# MongoDB and Mongo Express Services
  mongo:
    image: mongo
    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    volumes:
    - type: volume
      source: mongo-vol
      target: /data/db

  mongo-express:
    image: mongo-express
    restart: always

    ports:
      - 8081:8081

    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass

    depends_on:
      - mongo 
