FROM node:latest

# Install Python and system dependencies
RUN apt update && apt install -y \
    python3 \
    python3-pip \
    chromium \
    && rm -rf /var/lib/apt/lists/*

# Install pdfplumber and dependencies
RUN pip3 install --break-system-packages pdfplumber spacy && \
    python3 -m spacy download en_core_web_sm -- --break-system-packages
